"""add_yolo_models

Revision ID: 1e0117cd701b
Revises: 001_add_cameras
Create Date: 2026-06-14 16:58:24.479865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e0117cd701b'
down_revision: Union[str, None] = '001_add_cameras'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yolo_models',
    sa.Column('name', sa.String(length=100), nullable=False, comment='模型名称'),
    sa.Column('version', sa.String(length=50), nullable=False, comment='模型版本如yolov8n'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='模型文件路径(.pt)'),
    sa.Column('classes', sa.Text(), nullable=False, comment='可识别类别JSON数组'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detection_tasks',
    sa.Column('name', sa.String(length=100), nullable=False, comment='任务名称'),
    sa.Column('camera_id', sa.Integer(), nullable=False, comment='摄像头ID'),
    sa.Column('model_id', sa.Integer(), nullable=False, comment='YOLO模型ID'),
    sa.Column('target_classes', sa.Text(), nullable=False, comment='目标识别类别JSON数组'),
    sa.Column('interval_seconds', sa.Integer(), nullable=False, comment='识别间隔(秒)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('last_run_at', sa.String(length=30), nullable=True, comment='上次执行时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['yolo_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detection_results',
    sa.Column('task_id', sa.Integer(), nullable=False, comment='任务ID'),
    sa.Column('image_path', sa.String(length=500), nullable=False, comment='原始图片路径'),
    sa.Column('annotated_image_path', sa.String(length=500), nullable=True, comment='标注图片路径'),
    sa.Column('detections', sa.Text(), nullable=False, comment='识别结果JSON'),
    sa.Column('detected_count', sa.Integer(), nullable=False, comment='识别到的目标数'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['detection_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detection_results')
    op.drop_table('detection_tasks')
    op.drop_table('yolo_models')
    # ### end Alembic commands ###
