"""add_confidence

Revision ID: 9b6c2913083e
Revises: 1e0117cd701b
Create Date: 2026-06-14 23:10:02.627679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b6c2913083e'
down_revision: Union[str, None] = '1e0117cd701b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection_tasks', sa.Column('confidence', sa.Float(), nullable=False, server_default='0.5', comment='置信度阈值'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detection_tasks', 'confidence')
    # ### end Alembic commands ###
